package com.rxs.tutorsearch.states;

public enum BotState {
    START_STATE,
    ROLE_STATE,
    ADMIN_STATE,
    TUTOR_STATE,
    TUTOR_NAME_STATE,
    TUTOR_SUBJECT_STATE,
    TUTOR_DESCRIPTION_STATE,
    TUTOR_PRICE_STATE,
    TUTOR_WAIT_STATE,
    TUTOR_CHOOSE_VALUE_BALANCE_STATE,
    TUTOR_WAIT_CARD_NUMBER_STATE,
    STUDENT_STATE,
    STUDENT_CHOOSE_VALUE_BALANCE_STATE,
    STUDENT_SUBJECT_STATE,
    STUDENT_TUTORS_LIST_STATE,
    STUDENT_TUTOR_PROFILE_STATE,
    STUDENT_WAIT_TIME_STATE,
    STUDENT_WAIT_TUTOR_ANSWER_STATE,
    STUDENT_WAIT_REVIEW_STATE,
}
